include:
  - board: nice_nano_v2
    shield: mission_control_left
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: mission_control_right

  - board: nice_nano_v2
    shield: settings_reset
